/*
 * Copyright (c) 2008-2015 Institut National de l'Information Geographique et Forestiere (IGN) France.
 * Released under the BSD license.
 */
/**
 * Header: Geoportal Web 2D API
 */

(function() {
    /**
     * Before creating the Geoportal namespace, check to see if
     * Geoportal.singleFile is true.  This occurs if the
     * Geoportal/SingleFile.js script is included before this one - as is the
     * case with single file builds.
     *
     */
    var singleFile= (typeof(Geoportal)=="object" && Geoportal.singleFile);

    /**
     * Property: scriptName
     * {String} Relative path of this script.
     */
    var scriptName= (!singleFile) ? "lib/Geoportal.js" : "GeoportalExtended.js";

    /*
     * If window.Geoportal isn't set when this script (Geoportal.js) is
     * evaluated (and if singleFile is false) then this script will load
     * *all* Geoportal scripts. If window.Geoportal is set to an array
     * then this script will attempt to load scripts for each string of
     * the array, using the string as the src of the script.
     *
     * Example:
     * (code)
     *     <script type="text/javascript">
     *         window.Geoportal = [
     *             "Geoportal/Util.js"
     *         ];
     *     </script>
     *     <script type="text/javascript" src="../lib/Geoportal.js"></script>
     * (end)
     * In this example Geoportal.js will load Util.js only.
     */
    var jsFiles= window.Geoportal;

    /**
     * Namespace: Geoportal
     * The Geoportal API based on OpenLayers 2.12.
     *      Aims at providing fullfledge OpenLayers and Geoportail's
     *      capabilities.
     * The Geoportal object provides a namespace for all things Geoportal.
     * The Geoportal extended API provides all OpenLayers, Proj4JS and
     * Geoportal features.
     */
    window.Geoportal= {

        /**
         * Function: _getScriptLocation
         * Return the path to this script.
         *
         * Returns:
         * {String} Path to this script
         */
        _getScriptLocation: (function () {
            var scriptLocation= "";
            var isGP= new RegExp("(^|(.*?\\/))(" + scriptName + ")(\\?|$)");

            // From GeoExt :
            // If we load other scripts right before Geoportal using the same
            // mechanism to add script resources dynamically (e.g. OpenLayers),
            // document.getElementsByTagName will not find the GeoExt script tag
            // in FF2. Using document.documentElement.getElementsByTagName instead
            // works around this issue.
            var scripts= document.documentElement.getElementsByTagName('script');
            for (var i= 0, len= scripts.length; i<len; i++) {
                var src= scripts[i].getAttribute('src');
                if (src) {
                    var match= src.match(isGP);
                    if (match) {
                        scriptLocation= match[1];
                        break;
                    }
                }
            }
            return (function() { return scriptLocation; });
         })()
    };
    /**
     * Geoportal.singleFile is a flag indicating this file is being included
     * in a Single File Library build of the Geoportal Library.
     *
     * When we are *not* part of a SFL build we dynamically include the
     * Geoportal library code.
     *
     * When we *are* part of a SFL build we do not dynamically include the
     * Geoportal library code as it will be appended at the end of this file.
     */
    if(!singleFile) {
        if (!jsFiles) {
            jsFiles= [
                // OPENLAYERS:
                "../../openlayers/lib/OpenLayers/SingleFile.js",//make OpenLayers believes it is compacted!
                "../../openlayers/lib/OpenLayers/Animation.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/Class.js",
                "../../openlayers/lib/OpenLayers/BaseTypes.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/Bounds.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/Element.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/LonLat.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/Pixel.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/Size.js",
                "../../openlayers/lib/OpenLayers/Console.js",
                "../../openlayers/lib/OpenLayers/Lang.js",
                "../../openlayers/lib/OpenLayers/Util.js",
//                "../../openlayers/lib/Gears/gears_init.js", //Plus de Gears dans OL2.12=>utilisation de html5
                "../../openlayers/lib/OpenLayers/Protocol.js",
//                "../../openlayers/lib/OpenLayers/Protocol/SQL.js",
                "../../openlayers/lib/OpenLayers/Format.js",
                "../../openlayers/lib/OpenLayers/Format/JSON.js",
                "../../openlayers/lib/OpenLayers/Feature.js",
                "../../openlayers/lib/OpenLayers/Feature/Vector.js",
                "../../openlayers/lib/OpenLayers/Format/WKT.js",
//                "../../openlayers/lib/OpenLayers/Protocol/SQL/Gears.js",//Plus de Gears dans OL2.12=>utilisation de html5
                "../../openlayers/lib/OpenLayers/Format/XML.js",
                "../../openlayers/lib/OpenLayers/BaseTypes/Date.js",//NEW
                "../../openlayers/lib/OpenLayers/Geometry.js",
                "../../openlayers/lib/OpenLayers/Geometry/Point.js",
                "../../openlayers/lib/OpenLayers/Geometry/Collection.js",
                "../../openlayers/lib/OpenLayers/Geometry/MultiPoint.js",
                "../../openlayers/lib/OpenLayers/Geometry/Curve.js",
                "../../openlayers/lib/OpenLayers/Geometry/LineString.js",
                "../../openlayers/lib/OpenLayers/Geometry/LinearRing.js",
                "../../openlayers/lib/OpenLayers/Geometry/Polygon.js",
                "../../openlayers/lib/OpenLayers/Events.js",
                "../../openlayers/lib/OpenLayers/Events/buttonclick.js",
                "../../openlayers/lib/OpenLayers/Request.js",
                "../../openlayers/lib/OpenLayers/Request/XMLHttpRequest.js",
                "../../openlayers/lib/OpenLayers/Projection.js",
                "../../openlayers/lib/OpenLayers/Format/KML.js",
                "../../openlayers/lib/OpenLayers/Geometry/MultiLineString.js",
                "../../openlayers/lib/OpenLayers/Geometry/MultiPolygon.js",
                "../../openlayers/lib/OpenLayers/Format/GML.js",
                "../../openlayers/lib/OpenLayers/Format/GML/Base.js",
                "../../openlayers/lib/OpenLayers/Format/GML/v2.js",
                "../../openlayers/lib/OpenLayers/Style.js",
                "../../openlayers/lib/OpenLayers/Symbolizer.js",
                "../../openlayers/lib/OpenLayers/Symbolizer/Point.js",
                "../../openlayers/lib/OpenLayers/Symbolizer/Line.js",
                "../../openlayers/lib/OpenLayers/Symbolizer/Polygon.js",
                "../../openlayers/lib/OpenLayers/Symbolizer/Text.js",
                "../../openlayers/lib/OpenLayers/Symbolizer/Raster.js",
                "../../openlayers/lib/OpenLayers/Rule.js",
                "../../openlayers/lib/OpenLayers/Format/OGCExceptionReport.js",//NEW
                "../../openlayers/lib/OpenLayers/Format/XML/VersionedOGC.js",//NEW
                "../../openlayers/lib/OpenLayers/Filter.js",
                "../../openlayers/lib/OpenLayers/Filter/FeatureId.js",
                "../../openlayers/lib/OpenLayers/Filter/Logical.js",
                "../../openlayers/lib/OpenLayers/Filter/Comparison.js",
                "../../openlayers/lib/OpenLayers/Filter/Spatial.js",
                "../../openlayers/lib/OpenLayers/Format/SLD.js",
                "../../openlayers/lib/OpenLayers/Format/Filter.js",
                "../../openlayers/lib/OpenLayers/Filter/Function.js",//NEW
                "../../openlayers/lib/OpenLayers/Format/Filter/v1.js",
                "../../openlayers/lib/OpenLayers/Format/Filter/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Format/SLD/v1.js",
                "../../openlayers/lib/OpenLayers/Format/SLD/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Format/Context.js",
                "../../openlayers/lib/OpenLayers/Format/OWSContext.js",
                "../../openlayers/lib/OpenLayers/Format/OWSCommon.js",
                "../../openlayers/lib/OpenLayers/Format/OWSCommon/v1.js",
                "../../openlayers/lib/OpenLayers/Format/OWSCommon/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Format/OWSContext/v0_3_1.js",
                "../../openlayers/lib/OpenLayers/Format/CSWGetRecords.js",
                "../../openlayers/lib/OpenLayers/Tween.js",
                "../../openlayers/lib/OpenLayers/Map.js",
                "../../openlayers/lib/OpenLayers/Layer.js",
                "../../openlayers/lib/OpenLayers/Layer/SphericalMercator.js",
                "../../openlayers/lib/OpenLayers/Layer/EventPane.js",
                "../../openlayers/lib/OpenLayers/Layer/FixedZoomLevels.js",
                "../../openlayers/lib/OpenLayers/Layer/Google.js",
                "../../openlayers/lib/OpenLayers/Format/WFST.js",
                "../../openlayers/lib/OpenLayers/Format/WFST/v1.js",
                "../../openlayers/lib/OpenLayers/Format/GML/v3.js",
                "../../openlayers/lib/OpenLayers/Format/Filter/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/Format/WFST/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/Format/WFSCapabilities.js",
                "../../openlayers/lib/OpenLayers/Format/WFSCapabilities/v1.js",
//                "../../openlayers/lib/OpenLayers/Layer/VirtualEarth.js",
                "../../openlayers/lib/OpenLayers/Control.js",
                "../../openlayers/lib/OpenLayers/Control/Panel.js",
                "../../openlayers/lib/OpenLayers/Control/ZoomIn.js",
                "../../openlayers/lib/OpenLayers/Control/ZoomOut.js",
                "../../openlayers/lib/OpenLayers/Control/ZoomToMaxExtent.js",
                "../../openlayers/lib/OpenLayers/Control/ZoomPanel.js",
                "../../openlayers/lib/OpenLayers/Layer/HTTPRequest.js",
                "../../openlayers/lib/OpenLayers/Tile.js",
                "../../openlayers/lib/OpenLayers/Tile/Image.js",
                "../../openlayers/lib/OpenLayers/Layer/Grid.js",
                "../../openlayers/lib/OpenLayers/Format/ArcXML.js",
                "../../openlayers/lib/OpenLayers/Layer/ArcIMS.js",
                "../../openlayers/lib/OpenLayers/Format/WMSGetFeatureInfo.js",
                "../../openlayers/lib/OpenLayers/Format/OWSCommon/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/Format/WCSGetCoverage.js",//NEW
                "../../openlayers/lib/OpenLayers/Format/WPSExecute.js",//NEW
                "../../openlayers/lib/OpenLayers/Strategy.js",
                "../../openlayers/lib/OpenLayers/Strategy/Filter.js",
                "../../openlayers/lib/OpenLayers/Layer/Image.js",
                "../../openlayers/lib/OpenLayers/Strategy/Save.js",
                "../../openlayers/lib/OpenLayers/Format/WPSCapabilities.js",//NEW
                "../../openlayers/lib/OpenLayers/Renderer.js",
                "../../openlayers/lib/OpenLayers/Renderer/Canvas.js",
                "../../openlayers/lib/OpenLayers/Format/OSM.js",
                "../../openlayers/lib/OpenLayers/Layer/XYZ.js",
                "../../openlayers/lib/OpenLayers/Layer/OSM.js",//NEW
                "../../openlayers/lib/OpenLayers/Layer/Bing.js",//NEW
                "../../openlayers/lib/OpenLayers/Format/SOSGetFeatureOfInterest.js",
                "../../openlayers/lib/OpenLayers/Format/SOSGetObservation.js",
                "../../openlayers/lib/OpenLayers/Handler.js",
                "../../openlayers/lib/OpenLayers/Handler/MouseWheel.js",
                "../../openlayers/lib/OpenLayers/Format/WFST/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Renderer/Elements.js",
                "../../openlayers/lib/OpenLayers/Control/ArgParser.js",
                "../../openlayers/lib/OpenLayers/Control/Permalink.js",
                "../../openlayers/lib/OpenLayers/Layer/TMS.js",
                "../../openlayers/lib/OpenLayers/Strategy/Fixed.js",
                "../../openlayers/lib/OpenLayers/Format/WFSCapabilities/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/StyleMap.js",
                "../../openlayers/lib/OpenLayers/Layer/Vector.js",
                "../../openlayers/lib/OpenLayers/Layer/PointTrack.js",
                "../../openlayers/lib/OpenLayers/Protocol/WFS.js",
                "../../openlayers/lib/OpenLayers/Layer/Markers.js",
                "../../openlayers/lib/OpenLayers/Control/Pan.js",
                "../../openlayers/lib/OpenLayers/Layer/WMS.js",
//                "../../openlayers/lib/OpenLayers/Layer/WMS/Untiled.js",
//                "../../openlayers/lib/OpenLayers/Geometry/Surface.js", //Plus de Surface dans OL2.12
                "../../openlayers/lib/OpenLayers/Format/ArcXML/Features.js",
                "../../openlayers/lib/OpenLayers/Control/Snapping.js",
                "../../openlayers/lib/OpenLayers/Format/CSWGetDomain.js",
                "../../openlayers/lib/OpenLayers/Format/CSWGetDomain/v2_0_2.js",
                "../../openlayers/lib/OpenLayers/Format/Text.js",
                "../../openlayers/lib/OpenLayers/Layer/Text.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/Strategy/BBOX.js",
                "../../openlayers/lib/OpenLayers/Handler/Feature.js",
                "../../openlayers/lib/OpenLayers/Layer/Vector/RootContainer.js",
                "../../openlayers/lib/OpenLayers/Control/SelectFeature.js",
                "../../openlayers/lib/OpenLayers/Handler/Point.js",
                "../../openlayers/lib/OpenLayers/Handler/Path.js",
//                "../../openlayers/lib/OpenLayers/Layer/GML.js",
                "../../openlayers/lib/OpenLayers/Control/PanPanel.js",
                "../../openlayers/lib/OpenLayers/Control/Attribution.js",
//                "../../openlayers/lib/OpenLayers/Renderer/NG.js",//NEW
//                "../../openlayers/lib/OpenLayers/Renderer/SVG2.js",//NEW
                "../../openlayers/lib/OpenLayers/Kinetic.js",//NEW
//                "../../openlayers/lib/OpenLayers/Ajax.js",
                "../../openlayers/lib/OpenLayers/Layer/GeoRSS.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_3.js",
                "../../openlayers/lib/OpenLayers/Format/SOSCapabilities.js",
                "../../openlayers/lib/OpenLayers/Layer/KaMap.js",
                "../../openlayers/lib/OpenLayers/Format/WMC.js",
                "../../openlayers/lib/OpenLayers/Format/WMC/v1.js",
                "../../openlayers/lib/OpenLayers/Format/WMC/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/Popup.js",
                "../../openlayers/lib/OpenLayers/Popup/Anchored.js",
                "../../openlayers/lib/Rico/Color.js",
                "../../openlayers/lib/Rico/Corner.js",
                "../../openlayers/lib/OpenLayers/Popup/AnchoredBubble.js",
                "../../openlayers/lib/OpenLayers/Renderer/SVG.js",
                "../../openlayers/lib/OpenLayers/Format/WMSDescribeLayer.js",
                "../../openlayers/lib/OpenLayers/Format/WMSDescribeLayer/v1_1.js",
                "../../openlayers/lib/OpenLayers/Control/ScaleLine.js",
                "../../openlayers/lib/OpenLayers/Control/PanZoom.js",
                "../../openlayers/lib/OpenLayers/Popup/Framed.js",
                "../../openlayers/lib/OpenLayers/Format/GeoJSON.js",
                "../../openlayers/lib/OpenLayers/Strategy/Paging.js",
                "../../openlayers/lib/OpenLayers/Handler/Drag.js",
                "../../openlayers/lib/OpenLayers/Handler/Box.js",
                "../../openlayers/lib/OpenLayers/Control/ZoomBox.js",
                "../../openlayers/lib/OpenLayers/Control/DragPan.js",
                "../../openlayers/lib/OpenLayers/Handler/Click.js",
                "../../openlayers/lib/OpenLayers/Control/Navigation.js",
                "../../openlayers/lib/OpenLayers/Control/DrawFeature.js",
                "../../openlayers/lib/OpenLayers/Handler/Polygon.js",
                "../../openlayers/lib/OpenLayers/Control/EditingToolbar.js",
                "../../openlayers/lib/OpenLayers/Protocol/WFS/v1.js",
                "../../openlayers/lib/OpenLayers/Layer/WorldWind.js",
                "../../openlayers/lib/OpenLayers/Protocol/WFS/v1_1_0.js",
                "../../openlayers/lib/OpenLayers/Format/WMTSCapabilities.js",
                "../../openlayers/lib/OpenLayers/Layer/Google/v3.js",
                "../../openlayers/lib/OpenLayers/Format/WPSDescribeProcess.js",//NEW
                "../../openlayers/lib/OpenLayers/Control/PanZoomBar.js",
                "../../openlayers/lib/OpenLayers/Format/CSWGetRecords/v2_0_2.js",
                "../../openlayers/lib/OpenLayers/Handler/Hover.js",
                "../../openlayers/lib/OpenLayers/Control/WMTSGetFeatureInfo.js",
                "../../openlayers/lib/OpenLayers/Control/Scale.js",
                "../../openlayers/lib/OpenLayers/Layer/MapGuide.js",
                "../../openlayers/lib/OpenLayers/Control/Measure.js",
                "../../openlayers/lib/OpenLayers/Format/WMC/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Format/WMTSCapabilities/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Popup/FramedCloud.js",
//                "../../openlayers/lib/OpenLayers/Geometry/Rectangle.js",
//                "../../openlayers/lib/OpenLayers/Tile/WFS.js",
                "../../openlayers/lib/OpenLayers/Format/SOSCapabilities/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Handler/Pinch.js",//NEW
                "../../openlayers/lib/OpenLayers/Control/NavToolbar.js",
                "../../openlayers/lib/OpenLayers/Control/PinchZoom.js",//NEW
                "../../openlayers/lib/OpenLayers/Strategy/Refresh.js",
                "../../openlayers/lib/OpenLayers/Control/Geolocate.js",//NEW
                "../../openlayers/lib/OpenLayers/Layer/ArcGIS93Rest.js",
                "../../openlayers/lib/OpenLayers/Layer/MapServer.js",
//                "../../openlayers/lib/OpenLayers/Layer/MapServer/Untiled.js", //deprecated OL 2.12
                "../../openlayers/lib/OpenLayers/Control/GetFeature.js",
                "../../openlayers/lib/OpenLayers/Format/QueryStringFilter.js",//NEW
                "../../openlayers/lib/OpenLayers/Format/GeoRSS.js",
                "../../openlayers/lib/OpenLayers/Control/MousePosition.js",
                "../../openlayers/lib/OpenLayers/Control/Button.js",
                "../../openlayers/lib/OpenLayers/Control/NavigationHistory.js",
                "../../openlayers/lib/OpenLayers/Protocol/HTTP.js",
                "../../openlayers/lib/OpenLayers/Strategy/Cluster.js",
                "../../openlayers/lib/OpenLayers/Protocol/SOS.js",
                "../../openlayers/lib/OpenLayers/Format/WFSDescribeFeatureType.js",
                "../../openlayers/lib/OpenLayers/Control/OverviewMap.js",
                "../../openlayers/lib/OpenLayers/Format/WPSCapabilities/v1_0_0.js",//NEW
                "../../openlayers/lib/OpenLayers/Control/TouchNavigation.js",//NEW
                "../../openlayers/lib/OpenLayers/Style2.js",
                "../../openlayers/lib/OpenLayers/Control/DragFeature.js",
                "../../openlayers/lib/OpenLayers/Handler/Keyboard.js",
                "../../openlayers/lib/OpenLayers/Control/ModifyFeature.js",
                "../../openlayers/lib/OpenLayers/Format/WFS.js",
                "../../openlayers/lib/OpenLayers/Layer/Boxes.js",
                "../../openlayers/lib/OpenLayers/Format/WFSCapabilities/v1_0_0.js",
//                "../../openlayers/lib/OpenLayers/Layer/Yahoo.js",
                "../../openlayers/lib/OpenLayers/Layer/PointGrid.js",//NEW
                "../../openlayers/lib/OpenLayers/Layer/Zoomify.js",
                "../../openlayers/lib/OpenLayers/Layer/WMTS.js",
                "../../openlayers/lib/OpenLayers/Format/CQL.js",//NEW
                "../../openlayers/lib/OpenLayers/Renderer/VML.js",
//                "../../openlayers/lib/OpenLayers/Layer/MultiMap.js", //Plus dans OL2.12
                "../../openlayers/lib/OpenLayers/Protocol/WFS/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Handler/RegularPolygon.js",
                "../../openlayers/lib/OpenLayers/Control/SLDSelect.js",
                "../../openlayers/lib/OpenLayers/Control/Graticule.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1_1.js",
                "../../openlayers/lib/OpenLayers/Protocol/Script.js",//NEW
                "../../openlayers/lib/OpenLayers/Tile/Image/IFrame.js",
//                "../../openlayers/lib/OpenLayers/Layer/WMS/Post.js",
                "../../openlayers/lib/OpenLayers/Control/TransformFeature.js",
                "../../openlayers/lib/OpenLayers/Layer/ArcGISCache.js",//NEW
                "../../openlayers/lib/OpenLayers/Control/WMSGetFeatureInfo.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_3_0.js",
                "../../openlayers/lib/OpenLayers/Control/Split.js",
                "../../openlayers/lib/OpenLayers/Protocol/SOS/v1_0_0.js",
                "../../openlayers/lib/OpenLayers/Layer/KaMapCache.js",
                "../../openlayers/lib/OpenLayers/Layer/TileCache.js",
                "../../openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1_1_WMSC.js",//NEW
//                "../../openlayers/lib/OpenLayers/Layer/WFS.js",
                "../../openlayers/lib/OpenLayers/Control/LayerSwitcher.js",
                "../../openlayers/lib/OpenLayers/Format/Atom.js",
                "../../openlayers/lib/OpenLayers/Control/KeyboardDefaults.js",
//                "../../openlayers/lib/OpenLayers/Feature/WFS.js",
                //"../../openlayers/lib/OpenLayers/Format/GPX.js",
                //"../../openlayers/lib/OpenLayers/Format/XLS.js",//NEW
                //"../../openlayers/lib/OpenLayers/Format/XLS/v1.js",//NEW
                //"../../openlayers/lib/OpenLayers/Format/XLS/v1_1_0.js",//NEW
                "../../openlayers/lib/OpenLayers/Icon.js",
                "../../openlayers/lib/OpenLayers/Marker.js",
                "../../openlayers/lib/OpenLayers/Marker/Box.js",
                "../../openlayers/lib/OpenLayers/Lang/en.js",
                "../../openlayers/lib/OpenLayers/Lang/de.js",
                "../../openlayers/lib/OpenLayers/Lang/es.js",
                "../../openlayers/lib/OpenLayers/Lang/fr.js",
                "../../openlayers/lib/OpenLayers/Lang/it.js",
                // PROJ4JS:
                "../../proj4js/lib/proj4js.js",
                "../../proj4js/lib/OverloadedProj4js.js",
                "../../proj4js/lib/projCode/utm.js",
                "../../proj4js/lib/defs/EPSG32755.js",
                "../../proj4js/lib/projCode/lcc.js",
                "../../proj4js/lib/defs/IGNFETRS89LCC.js",
                "../../proj4js/lib/defs/EPSG32631.js",
                "../../proj4js/lib/defs/EPSG32722.js",
                "../../proj4js/lib/defs/EPSG32727.js",
                "../../proj4js/lib/projCode/longlat.js",
//                "../../proj4js/lib/defs/IGNFMART38GEO.js",
                "../../proj4js/lib/projCode/tmerc.js",
                "../../proj4js/lib/defs/IGNFRGM04UTM38S.js",
                "../../proj4js/lib/projCode/eqc.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALPYF.js",
                "../../proj4js/lib/defs/IGNFUTM33ETRS89.js",
//                "../../proj4js/lib/projCode/geocent.js",
//                "../../proj4js/lib/defs/IGNFTERA50.js",
                "../../proj4js/lib/defs/EPSG32630.js",
                "../../proj4js/lib/defs/EPSG32747.js",
                "../../proj4js/lib/defs/EPSG32757.js",
                "../../proj4js/lib/defs/EPSG2989.js",
                "../../proj4js/lib/defs/EPSG3297.js",
                "../../proj4js/lib/defs/EPSG310642801.js",
                "../../proj4js/lib/defs/IGNFTAHI51UTM06S.js",
                "../../proj4js/lib/defs/EPSG27584.js",
                "../../proj4js/lib/defs/IGNFWALL78UTM1S.js",
                "../../proj4js/lib/defs/EPSG32716.js",
                "../../proj4js/lib/defs/EPSG32734.js",
                "../../proj4js/lib/defs/EPSG32609.js",
                "../../proj4js/lib/defs/EPSG32641.js",
                "../../proj4js/lib/defs/EPSG32720.js",
//                "../../proj4js/lib/defs/IGNFREUN47.js",
                "../../proj4js/lib/defs/EPSG32650.js",
                "../../proj4js/lib/defs/IGNFRGPFUTM5S.js",
                "../../proj4js/lib/defs/EPSG32759.js",
                "../../proj4js/lib/defs/EPSG3034.js",
                "../../proj4js/lib/defs/EPSG3298.js",
                "../../proj4js/lib/defs/EPSG32626.js",
                "../../proj4js/lib/defs/IGNFLAMB1.js",
                "../../proj4js/lib/defs/EPSG4632.js",
                "../../proj4js/lib/defs/EPSG32648.js",
                "../../proj4js/lib/defs/EPSG32652.js",
                "../../proj4js/lib/defs/EPSG3172.js",
                "../../proj4js/lib/defs/IGNFUTM37ETRS89.js",
                "../../proj4js/lib/defs/EPSG2995.js",
                "../../proj4js/lib/defs/EPSG32642.js",
                "../../proj4js/lib/defs/EPSG4627.js",
                "../../proj4js/lib/defs/EPSG3296.js",
                "../../proj4js/lib/defs/EPSG4637.js",
                "../../proj4js/lib/defs/EPSG4467.js",
                "../../proj4js/lib/defs/IGNFCSG67.js",
                "../../proj4js/lib/defs/EPSG32730.js",
                "../../proj4js/lib/defs/EPSG27572.js",
                "../../proj4js/lib/defs/IGNFETRS89GEO.js",
                "../../proj4js/lib/defs/EPSG32657.js",
                "../../proj4js/lib/defs/EPSG32646.js",
                "../../proj4js/lib/defs/EPSG32714.js",
                "../../proj4js/lib/defs/EPSG27573.js",
//                "../../proj4js/lib/defs/IGNFSTPM50.js",
                "../../proj4js/lib/defs/IGNFCROZ63.js",
                "../../proj4js/lib/defs/EPSG4322.js",
                "../../proj4js/lib/defs/EPSG3299.js",
                "../../proj4js/lib/defs/EPSG27564.js",
                "../../proj4js/lib/projCode/vandg.js",
                "../../proj4js/lib/defs/EPSG310706808.js",
                "../../proj4js/lib/defs/EPSG4235.js",
//                "../../proj4js/lib/defs/IGNFSTPL69UTM43S.js",
                "../../proj4js/lib/defs/IGNFLAMB3.js",
                "../../proj4js/lib/defs/EPSG32624.js",
                "../../proj4js/lib/defs/IGNFUTM20W84MART.js",
                "../../proj4js/lib/defs/EPSG5490.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALMYT.js",
                "../../proj4js/lib/defs/EPSG32760.js",
                "../../proj4js/lib/defs/EPSG32643.js",
                "../../proj4js/lib/defs/IGNFRGSPM06GEO.js",
//                "../../proj4js/lib/defs/IGNFWGS72.js",
                "../../proj4js/lib/projCode/merc.js",
                "../../proj4js/lib/defs/EPSG3727.js",
                "../../proj4js/lib/projCode/gstmerc.js",
                "../../proj4js/lib/defs/EPSG32726.js",
                "../../proj4js/lib/defs/EPSG32617.js",
                "../../proj4js/lib/defs/EPSG32627.js",
//                "../../proj4js/lib/defs/IGNFGUADFM49U20.js",
                "../../proj4js/lib/defs/EPSG32732.js",
                "../../proj4js/lib/defs/EPSG310547809.js",
                "../../proj4js/lib/defs/EPSG32649.js",
                "../../proj4js/lib/defs/IGNFUTM30ETRS89.js",
                "../../proj4js/lib/defs/EPSG32709.js",
                "../../proj4js/lib/defs/EPSG4634.js",
                "../../proj4js/lib/defs/EPSG4150.js",
//                "../../proj4js/lib/defs/IGNFNTF.js",
                "../../proj4js/lib/defs/IGNFUTM26ETRS89.js",
                "../../proj4js/lib/defs/EPSG32620.js",
                "../../proj4js/lib/defs/IGNFUTM38ETRS89.js",
                "../../proj4js/lib/defs/EPSG32616.js",
                "../../proj4js/lib/defs/EPSG2969.js",
                "../../proj4js/lib/defs/EPSG310700806.js",
                "../../proj4js/lib/defs/EPSG25832.js",
                "../../proj4js/lib/defs/EPSG32702.js",
                "../../proj4js/lib/defs/EPSG32602.js",
                "../../proj4js/lib/projCode/aeqd.js",
//                "../../proj4js/lib/defs/IGNFCSG67GEO.js",
//                "../../proj4js/lib/defs/IGNFKERG62CAR.js",
                "../../proj4js/lib/defs/IGNFCSG67UTM21.js",
                "../../proj4js/lib/defs/EPSG32725.js",
                "../../proj4js/lib/defs/EPSG2154.js",
//                "../../proj4js/lib/defs/IGNFWGS84.js",
                "../../proj4js/lib/defs/EPSG32635.js",
                "../../proj4js/lib/defs/EPSG32729.js",
                "../../proj4js/lib/defs/IGNFUTM35ETRS89.js",
                "../../proj4js/lib/projCode/somerc.js",
                "../../proj4js/lib/defs/EPSG32752.js",
                "../../proj4js/lib/projCode/gnom.js",
                "../../proj4js/lib/defs/EPSG32625.js",
                "../../proj4js/lib/defs/EPSG4230.js",
                "../../proj4js/lib/defs/EPSG4630.js",
                "../../proj4js/lib/defs/EPSG32655.js",
                "../../proj4js/lib/defs/EPSG2987.js",
                "../../proj4js/lib/defs/IGNFTAHI79GEO.js",
                "../../proj4js/lib/projCode/cea.js",
                "../../proj4js/lib/defs/EPSG3171.js",
                "../../proj4js/lib/defs/EPSG2970.js",
                "../../proj4js/lib/defs/IGNFIGN63GEO.js",
                "../../proj4js/lib/defs/IGNFSTPM50GEO.js",
                "../../proj4js/lib/defs/EPSG32717.js",
                "../../proj4js/lib/defs/EPSG32743.js",
                "../../proj4js/lib/defs/IGNFUTM20W84GUAD.js",
                "../../proj4js/lib/defs/EPSG3044.js",
                "../../proj4js/lib/defs/EPSG32735.js",
                "../../proj4js/lib/defs/EPSG3169.js",
                "../../proj4js/lib/defs/EPSG310024802.js",
                "../../proj4js/lib/defs/EPSG2977.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALASP.js",
                "../../proj4js/lib/defs/IGNFLAMB4.js",
                "../../proj4js/lib/defs/EPSG4638.js",
//                "../../proj4js/lib/defs/IGNFRGM04.js",
                "../../proj4js/lib/defs/EPSG32756.js",
                "../../proj4js/lib/defs/EPSG2980.js",
                "../../proj4js/lib/defs/EPSG3042.js",
                "../../proj4js/lib/defs/EPSG32637.js",
                "../../proj4js/lib/defs/EPSG32629.js",
                "../../proj4js/lib/defs/IGNFUTM01SW84.js",
                "../../proj4js/lib/defs/IGNFRGSPM06U21.js",
                "../../proj4js/lib/defs/EPSG3163.js",
                "../../proj4js/lib/defs/IGNFGUAD48GEO.js",
                "../../proj4js/lib/defs/EPSG3166.js",
                "../../proj4js/lib/defs/EPSG4749.js",
                "../../proj4js/lib/defs/EPSG310702807.js",
//                "../../proj4js/lib/defs/IGNFRGR92.js",
                "../../proj4js/lib/defs/EPSG2972.js",
                "../../proj4js/lib/defs/EPSG32656.js",
                "../../proj4js/lib/defs/EPSG2990.js",
                "../../proj4js/lib/defs/EPSG32715.js",
                "../../proj4js/lib/defs/EPSG310915814.js",
                "../../proj4js/lib/defs/EPSG4258.js",
                "../../proj4js/lib/defs/EPSG27591.js",
                "../../proj4js/lib/defs/IGNFLAMB2C.js",
                "../../proj4js/lib/defs/EPSG3395.js",
                "../../proj4js/lib/defs/EPSG32658.js",
//                "../../proj4js/lib/defs/IGNFED50G.js",
                "../../proj4js/lib/defs/IGNFXGEO.js",
                "../../proj4js/lib/defs/EPSG32618.js",
                "../../proj4js/lib/projCode/ortho.js",
                "../../proj4js/lib/defs/EPSG32623.js",
                "../../proj4js/lib/defs/EPSG4687.js",
                "../../proj4js/lib/defs/EPSG32742.js",
                "../../proj4js/lib/defs/IGNFLAMB1C.js",
                "../../proj4js/lib/defs/EPSG32608.js",
                "../../proj4js/lib/defs/EPSG32754.js",
                "../../proj4js/lib/defs/EPSG21781.js",
                "../../proj4js/lib/defs/EPSG3170.js",
//                "../../proj4js/lib/defs/IGNFRGNC.js",
                "../../proj4js/lib/defs/IGNFMOOREA87U6S.js",
                "../../proj4js/lib/defs/EPSG2978.js",
                "../../proj4js/lib/defs/EPSG2213.js",
                "../../proj4js/lib/defs/EPSG25831.js",
                "../../proj4js/lib/projCode/gauss.js",
                "../../proj4js/lib/defs/IGNFRGPFUTM7S.js",
                "../../proj4js/lib/defs/EPSG32749.js",
                "../../proj4js/lib/defs/EPSG32651.js",
                "../../proj4js/lib/defs/EPSG32724.js",
                "../../proj4js/lib/defs/EPSG32653.js",
                "../../proj4js/lib/defs/IGNFRGF93CC49.js",
                "../../proj4js/lib/defs/IGNFKERG62UTM42S.js",
                "../../proj4js/lib/defs/EPSG27583.js",
                "../../proj4js/lib/defs/EPSG32719.js",
                "../../proj4js/lib/defs/IGNFRGR92UTM40S.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALFXX.js",
                "../../proj4js/lib/defs/IGNFWGS84WMSV.js",
                "../../proj4js/lib/defs/EPSG27581.js",
                "../../proj4js/lib/defs/EPSG4622.js",
                "../../proj4js/lib/projCode/poly.js",
                "../../proj4js/lib/defs/EPSG32710.js",
                "../../proj4js/lib/defs/IGNFLAMB2.js",
                "../../proj4js/lib/defs/EPSG32613.js",
                "../../proj4js/lib/defs/IGNFRGF93CC50.js",
                "../../proj4js/lib/defs/IGNFGUADFM49.js",
                "../../proj4js/lib/defs/EPSG32736.js",
                "../../proj4js/lib/defs/IGNFRGF93CC46.js",
                "../../proj4js/lib/defs/IGNFUTM32ETRS89.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALSPM.js",
                "../../proj4js/lib/defs/IGNFLAMB3C.js",
                "../../proj4js/lib/defs/IGNFAMST63GEO.js",
                "../../proj4js/lib/defs/EPSG2982.js",
                "../../proj4js/lib/defs/EPSG4326.js",
                "../../proj4js/lib/defs/EPSG32654.js",
                "../../proj4js/lib/defs/IGNFLAMBE.js",
                "../../proj4js/lib/defs/EPSG3312.js",
                "../../proj4js/lib/defs/IGNFKERG62GEO.js",
                "../../proj4js/lib/defs/EPSG32728.js",
                "../../proj4js/lib/defs/EPSG32701.js",
                "../../proj4js/lib/defs/EPSG32634.js",
                "../../proj4js/lib/defs/EPSG32638.js",
                "../../proj4js/lib/defs/CRS84.js",
                "../../proj4js/lib/defs/EPSG3306.js",
                "../../proj4js/lib/defs/EPSG32723.js",
                "../../proj4js/lib/defs/EPSG3304.js",
                "../../proj4js/lib/defs/EPSG32753.js",
                "../../proj4js/lib/defs/IGNFSTPL69GEO.js",
                "../../proj4js/lib/defs/IGNFMART38.js",
                "../../proj4js/lib/defs/EPSG2975.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALANF.js",
                "../../proj4js/lib/defs/EPSG25830.js",
                "../../proj4js/lib/defs/EPSG27571.js",
                "../../proj4js/lib/defs/IGNFMART38UTM20.js",
                "../../proj4js/lib/defs/IGNFMOOREA87GEO.js",
//                "../../proj4js/lib/defs/IGNFRRAF91.js",
                "../../proj4js/lib/defs/EPSG4698.js",
//                "../../proj4js/lib/defs/IGNFIGN72GEO.js",
                "../../proj4js/lib/defs/EPSG32611.js",
                "../../proj4js/lib/defs/EPSG32748.js",
                "../../proj4js/lib/defs/IGNFRGF93CC48.js",
                "../../proj4js/lib/defs/EPSG27582.js",
                "../../proj4js/lib/defs/EPSG4275.js",
                "../../proj4js/lib/defs/IGNFNTFP.js",
                "../../proj4js/lib/defs/EPSG2976.js",
                "../../proj4js/lib/defs/EPSG4151.js",
                "../../proj4js/lib/projCode/cass.js",
                "../../proj4js/lib/defs/IGNFSTPL69.js",
                "../../proj4js/lib/projCode/omerc.js",
                "../../proj4js/lib/defs/IGNFREUN47GAUSSL.js",
                "../../proj4js/lib/defs/IGNFGUADFM49GEO.js",
//                "../../proj4js/lib/defs/IGNFRGPF.js",
                "../../proj4js/lib/defs/EPSG32741.js",
                "../../proj4js/lib/defs/EPSG32739.js",
                "../../proj4js/lib/defs/EPSG2981.js",
                "../../proj4js/lib/defs/EPSG32636.js",
                "../../proj4js/lib/defs/EPSG32647.js",
//                "../../proj4js/lib/defs/IGNFCROZ63GEO.js",
                "../../proj4js/lib/defs/IGNFUTM29ETRS89.js",
                "../../proj4js/lib/defs/IGNFUTM42SW84.js",
                "../../proj4js/lib/defs/IGNFUTM36ETRS89.js",
                "../../proj4js/lib/defs/EPSG4641.js",
                "../../proj4js/lib/defs/EPSG3313.js",
                "../../proj4js/lib/defs/EPSG4171.js",
                "../../proj4js/lib/defs/EPSG32607.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALGUF.js",
                "../../proj4js/lib/defs/EPSG32711.js",
                "../../proj4js/lib/defs/IGNFRGF93CC44.js",
                "../../proj4js/lib/defs/EPSG32744.js",
                "../../proj4js/lib/defs/IGNFIGN72UTM58S.js",
                "../../proj4js/lib/defs/IGNFUTM22RGFG95.js",
                "../../proj4js/lib/defs/EPSG3165.js",
                "../../proj4js/lib/defs/EPSG4691.js",
                "../../proj4js/lib/defs/EPSG4474.js",
                "../../proj4js/lib/defs/IGNFTAHI79.js",
                "../../proj4js/lib/defs/EPSG4471.js",
//                "../../proj4js/lib/defs/IGNFTAHAA.js",
                "../../proj4js/lib/defs/EPSG4628.js",
//                "../../proj4js/lib/defs/IGNFAMST63.js",
                "../../proj4js/lib/projCode/stere.js",
                "../../proj4js/lib/defs/EPSG2986.js",
                "../../proj4js/lib/defs/EPSG32621.js",
                "../../proj4js/lib/defs/EPSG310642812.js",
//                "../../proj4js/lib/defs/IGNFRGSPM06.js",
                "../../proj4js/lib/defs/EPSG310642810.js",
                "../../proj4js/lib/projCode/sterea.js",
                "../../proj4js/lib/projCode/equi.js",
//                "../../proj4js/lib/defs/IGNFNUKU72GEO.js",
                "../../proj4js/lib/defs/EPSG3303.js",
                "../../proj4js/lib/defs/EPSG2973.js",
                "../../proj4js/lib/defs/EPSG32644.js",
                "../../proj4js/lib/defs/EPSG27574.js",
                "../../proj4js/lib/defs/EPSG27561.js",
                "../../proj4js/lib/defs/EPSG27563.js",
                "../../proj4js/lib/defs/IGNFMAYO50GEO.js",
                "../../proj4js/lib/defs/EPSG310032811.js",
                "../../proj4js/lib/defs/EPSG32750.js",
                "../../proj4js/lib/defs/EPSG310486805.js",
                "../../proj4js/lib/defs/EPSG32740.js",
                "../../proj4js/lib/defs/EPSG4626.js",
                "../../proj4js/lib/projCode/sinu.js",
                "../../proj4js/lib/defs/EPSG32746.js",
                "../../proj4js/lib/defs/EPSG3302.js",
                "../../proj4js/lib/defs/EPSG4662.js",
                "../../proj4js/lib/defs/IGNFUTM27ETRS89.js",
                "../../proj4js/lib/defs/IGNFUTM39SW84.js",
//                "../../proj4js/lib/defs/IGNFRGFG95.js",
//                "../../proj4js/lib/defs/IGNFMAYO50.js",
                "../../proj4js/lib/defs/EPSG4750.js",
                "../../proj4js/lib/defs/EPSG32612.js",
                "../../proj4js/lib/defs/EPSG32660.js",
                "../../proj4js/lib/defs/EPSG32737.js",
                "../../proj4js/lib/projCode/laea.js",
                "../../proj4js/lib/defs/EPSG2971.js",
                "../../proj4js/lib/defs/IGNFMAYO50UTM38S.js",
                "../../proj4js/lib/defs/EPSG2984.js",
                "../../proj4js/lib/defs/EPSG4807.js",
//                "../../proj4js/lib/defs/IGNFWALL78GEO.js",
//                "../../proj4js/lib/defs/IGNFRGF93CC43.js",
                "../../proj4js/lib/defs/EPSG32718.js",
                "../../proj4js/lib/defs/IGNFTERA50G.js",
                "../../proj4js/lib/projCode/nzmg.js",
                "../../proj4js/lib/defs/EPSG4629.js",
                "../../proj4js/lib/defs/IGNFWALL78.js",
                "../../proj4js/lib/defs/IGNFRGR92GEO.js",
                "../../proj4js/lib/defs/IGNFUTM31ETRS89.js",
                "../../proj4js/lib/defs/EPSG310642813.js",
                "../../proj4js/lib/defs/IGNFWGS84RRAFGEO.js",
                "../../proj4js/lib/defs/EPSG4559.js",
                "../../proj4js/lib/defs/IGNFREUN47GEO.js",
                "../../proj4js/lib/defs/IGNFRGNCUTM59S.js",
                "../../proj4js/lib/defs/IGNFUTM28ETRS89.js",
                "../../proj4js/lib/defs/EPSG32705.js",
                "../../proj4js/lib/defs/EPSG32628.js",
                "../../proj4js/lib/defs/EPSG32604.js",
                "../../proj4js/lib/defs/IGNFTAHAAUTM05S.js",
                "../../proj4js/lib/defs/EPSG32610.js",
                "../../proj4js/lib/defs/EPSG32619.js",
                "../../proj4js/lib/defs/EPSG4645.js",
                "../../proj4js/lib/defs/EPSG32645.js",
                "../../proj4js/lib/defs/EPSG32639.js",
                "../../proj4js/lib/defs/EPSG3336.js",
                "../../proj4js/lib/projCode/mill.js",
                "../../proj4js/lib/defs/EPSG310642901.js",
                "../../proj4js/lib/defs/EPSG4621.js",
                "../../proj4js/lib/defs/IGNFWGS84G.js",
                "../../proj4js/lib/defs/EPSG4624.js",
                "../../proj4js/lib/defs/IGNFTAHAAGEO.js",
                "../../proj4js/lib/defs/EPSG32633.js",
                "../../proj4js/lib/defs/IGNFRGNCGEO.js",
                "../../proj4js/lib/defs/IGNFLAMB93.js",
                "../../proj4js/lib/defs/EPSG32761.js",
                "../../proj4js/lib/defs/EPSG32661.js",
                "../../proj4js/lib/defs/EPSG32632.js",
                "../../proj4js/lib/defs/IGNFLAMB4C.js",
                "../../proj4js/lib/defs/EPSG32659.js",
                "../../proj4js/lib/defs/EPSG32601.js",
                "../../proj4js/lib/defs/EPSG4558.js",
                "../../proj4js/lib/defs/EPSG27592.js",
                "../../proj4js/lib/defs/IGNFRGFG95GEO.js",
                "../../proj4js/lib/defs/EPSG3060.js",
                "../../proj4js/lib/defs/IGNFRGNCUTM57S.js",
                "../../proj4js/lib/defs/EPSG4640.js",
                "../../proj4js/lib/defs/IGNFETRS89LAEA.js",
                "../../proj4js/lib/defs/EPSG32707.js",
                "../../proj4js/lib/defs/EPSG4689.js",
                "../../proj4js/lib/defs/EPSG4623.js",
                "../../proj4js/lib/defs/IGNFCSG67UTM22.js",
                "../../proj4js/lib/defs/IGNFRGPFUTM6S.js",
                "../../proj4js/lib/defs/EPSG32733.js",
                "../../proj4js/lib/projCode/eqdc.js",
                "../../proj4js/lib/defs/EPSG32712.js",
                "../../proj4js/lib/defs/EPSG32704.js",
                "../../proj4js/lib/defs/EPSG32708.js",
                "../../proj4js/lib/defs/EPSG27562.js",
                "../../proj4js/lib/defs/EPSG32605.js",
                "../../proj4js/lib/defs/EPSG3305.js",
                "../../proj4js/lib/defs/IGNFGUAD48UTM20.js",
                "../../proj4js/lib/defs/IGNFRGPFGEO.js",
                "../../proj4js/lib/defs/IGNFRGF93CC47.js",
                "../../proj4js/lib/defs/EPSG32603.js",
                "../../proj4js/lib/defs/IGNFSTPM50UTM21.js",
                "../../proj4js/lib/defs/IGNFTAHI79UTM6S.js",
                "../../proj4js/lib/defs/EPSG32703.js",
//                "../../proj4js/lib/defs/IGNFIGN63.js",
                "../../proj4js/lib/defs/EPSG32713.js",
                "../../proj4js/lib/defs/EPSG32622.js",
                "../../proj4js/lib/defs/EPSG32751.js",
                "../../proj4js/lib/defs/EPSG32738.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALWLF.js",
                "../../proj4js/lib/defs/EPSG32731.js",
//                "../../proj4js/lib/defs/IGNFETRS89.js",
                "../../proj4js/lib/defs/EPSG3035.js",
                "../../proj4js/lib/defs/IGNFNUKU72U7S.js",
                "../../proj4js/lib/defs/IGNFRGTAAF07G.js",
                "../../proj4js/lib/defs/IGNFAMST63UTM43S.js",
                "../../proj4js/lib/defs/IGNFNTFG.js",
                "../../proj4js/lib/defs/IGNFRGF93CC42.js",
                "../../proj4js/lib/defs/EPSG4149.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALREU.js",
                "../../proj4js/lib/defs/EPSG32706.js",
                "../../proj4js/lib/defs/EPSG32758.js",
                "../../proj4js/lib/defs/EPSG3164.js",
                "../../proj4js/lib/defs/IGNFIGN63UTM7S.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALCRZ.js",
                "../../proj4js/lib/defs/IGNFRGM04GEO.js",
                "../../proj4js/lib/defs/IGNFMILLER.js",
                "../../proj4js/lib/defs/EPSG32606.js",
                "../../proj4js/lib/defs/EPSG4692.js",
                "../../proj4js/lib/defs/EPSG32662.js",
                "../../proj4js/lib/defs/EPSG2056.js",
//                "../../proj4js/lib/defs/IGNFMOOREA87.js",
                "../../proj4js/lib/defs/EPSG4625.js",
                "../../proj4js/lib/defs/IGNFGUAD48.js",
                "../../proj4js/lib/projCode/moll.js",
                "../../proj4js/lib/projCode/aea.js",
                "../../proj4js/lib/defs/EPSG3043.js",
                "../../proj4js/lib/defs/IGNFED50.js",
                "../../proj4js/lib/defs/IGNFRGF93.js",
                "../../proj4js/lib/defs/IGNFUTM34ETRS89.js",
                "../../proj4js/lib/defs/IGNFRGNCUTM58S.js",
                "../../proj4js/lib/defs/EPSG32615.js",
                "../../proj4js/lib/defs/IGNFCROZ63UTM39S.js",
                "../../proj4js/lib/defs/EPSG4633.js",
                "../../proj4js/lib/defs/EPSG27594.js",
                "../../proj4js/lib/defs/EPSG32614.js",
                "../../proj4js/lib/defs/IGNFNUKU72.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALKER.js",
                "../../proj4js/lib/defs/IGNFWGS72G.js",
                "../../proj4js/lib/defs/IGNFUTM43SW84.js",
//                "../../proj4js/lib/defs/IGNFRGTAAF07.js",
                "../../proj4js/lib/defs/IGNFIGN72.js",
                "../../proj4js/lib/defs/EPSG27593.js",
                "../../proj4js/lib/defs/IGNFTERA50STEREO.js",
                "../../proj4js/lib/defs/EPSG32745.js",
                "../../proj4js/lib/defs/IGNFRGF93CC45.js",
                "../../proj4js/lib/defs/EPSG32640.js",
                "../../proj4js/lib/defs/IGNFGEOPORTALNCL.js",
                "../../proj4js/lib/defs/IGNFRGF93G.js",
                "../../proj4js/lib/defs/EPSG32721.js",
                "../../proj4js/lib/defs/EPSG4690.js",
                "../../proj4js/lib/defs/EPSG3038.js",
                "../../proj4js/lib/defs/EPSG3039.js",
                "../../proj4js/lib/defs/EPSG3040.js",
                "../../proj4js/lib/defs/EPSG3041.js",
                "../../proj4js/lib/defs/EPSG3042.js",
                "../../proj4js/lib/defs/EPSG3043.js",
                "../../proj4js/lib/defs/EPSG3044.js",
                "../../proj4js/lib/defs/EPSG3045.js",
                "../../proj4js/lib/defs/EPSG3046.js",
                "../../proj4js/lib/defs/EPSG3047.js",
                "../../proj4js/lib/defs/EPSG3048.js",
                "../../proj4js/lib/defs/EPSG3049.js",
                "../../proj4js/lib/defs/EPSG3050.js",
                "../../proj4js/lib/defs/EPSG3051.js",
                "../../proj4js/lib/defs/EPSG25828.js",
                "../../proj4js/lib/defs/EPSG25829.js",
                "../../proj4js/lib/defs/EPSG25830.js",
                "../../proj4js/lib/defs/EPSG25831.js",
                "../../proj4js/lib/defs/EPSG25832.js",
                "../../proj4js/lib/defs/EPSG25833.js",
                "../../proj4js/lib/defs/EPSG25834.js",
                "../../proj4js/lib/defs/EPSG25835.js",
                "../../proj4js/lib/defs/EPSG25836.js",
                "../../proj4js/lib/defs/EPSG25837.js",
                "../../proj4js/lib/defs/EPSG25838.js",
                "../../proj4js/lib/defs/EPSG5489.js",
                "../../proj4js/lib/defs/EPSG4470.js",
                "proj4js/defs/ntf_r93.gsb.js",
                // FLEX:
                // no more flex on extended API
                // "../../flex/lib/swfobject.js",
                // GEOPORTAL:
                "OpenLayers/OverloadedOpenLayersMinimum.js",
                "OpenLayers/OverloadedOpenLayersStandard.js",
                "OpenLayers/OverloadedOpenLayersExtended.js",
                "OpenLayers/Format/GML/v3_2_1.js",//Experimental
                "OpenLayers/Format/Filter/v2.js",//Experimental
                "OpenLayers/Format/Filter/v2_0_0.js",//Experimental
                "OpenLayers/Format/WFST/v2.js",//Experimental
                "OpenLayers/Format/WFST/v2_0_0.js",//Experimental
                "OpenLayers/Protocol/WFS/v2.js",//Experimental
                "OpenLayers/Protocol/WFS/v2_0_0.js",//Experimental
                "Geoportal/Lang.js",
                "Geoportal/Lang/en.js",
                "Geoportal/Lang/fr.js",
                "Geoportal/Lang/de.js",
                "Geoportal/Lang/es.js",
                "Geoportal/Lang/it.js",
                "Geoportal/Layer.js",
                "Geoportal/Format.js",
                "Geoportal/Format/XLS.js",
                "Geoportal/Format/GASR.js",
                "Geoportal/OLS.js",
                "Geoportal/OLS/XLS.js",
                "Geoportal/OLS/AbstractHeader.js",
                "Geoportal/OLS/Error.js",
                "Geoportal/OLS/ErrorList.js",
                "Geoportal/OLS/ResponseHeader.js",
                "Geoportal/OLS/AbstractBody.js",
                "Geoportal/OLS/AbstractResponseParameters.js",
                "Geoportal/OLS/Response.js",
                "Geoportal/Format/XLS/v1_1.js",
                "Geoportal/OLS/AbstractRequestParameters.js",
                "Geoportal/OLS/LUS.js",
                "Geoportal/OLS/AbstractLocation.js",
                "Geoportal/OLS/AbstractAddress.js",
                "Geoportal/OLS/AbstractStreetLocator.js",
                "Geoportal/OLS/Street.js",
                "Geoportal/OLS/StreetAddress.js",
                "Geoportal/OLS/Place.js",
                "Geoportal/OLS/PostalCode.js",
                "Geoportal/OLS/Address.js",
                "Geoportal/OLS/LUS/GeocodeRequest.js",
                "Geoportal/OLS/GeocodeMatchCode.js",
                "Geoportal/OLS/LUS/GeocodedAddress.js",
                "Geoportal/OLS/LUS/GeocodeResponseList.js",
                "Geoportal/OLS/LUS/GeocodeResponse.js",
                "Geoportal/OLS/AbstractPosition.js",
                "Geoportal/OLS/UOM.js",
                "Geoportal/OLS/UOM/AbstractMeasure.js",
                "Geoportal/OLS/UOM/Distance.js",
                "Geoportal/OLS/UOM/Angle.js",
                "Geoportal/OLS/HorizontalAcc.js",
                "Geoportal/OLS/VerticalAcc.js",
                "Geoportal/OLS/QualityOfPosition.js",
                "Geoportal/OLS/UOM/TimeStamp.js",
                "Geoportal/OLS/UOM/Time.js",
                "Geoportal/OLS/UOM/Speed.js",
                "Geoportal/OLS/Position.js",
                "Geoportal/OLS/LUS/ReverseGeocodePreference.js",
                "Geoportal/OLS/LUS/ReverseGeocodeRequest.js",
                "Geoportal/OLS/LUS/SearchCentreDistance.js",
                "Geoportal/OLS/LUS/ReverseGeocodedLocation.js",
                "Geoportal/OLS/LUS/ReverseGeocodeResponse.js",
                "Geoportal/Format/XLS/v1_1/LocationUtilityService.js",
                "Geoportal/Format/XLS/v1_0.js",
                "Geoportal/Format/XLS/v1_0/LocationUtilityService.js",
                "Geoportal/Layer/OpenLS.js",
                "Geoportal/Layer/OpenLS/Core.js",
                "Geoportal/Format/GPX.js",
                "Geoportal/Format/GPX/v1.js",
                "Geoportal/Format/GPX/v1_1.js",
                "Geoportal/UI.js",
                "Geoportal/Control.js",
                "Geoportal/Control/SliderBase.js",
                "Geoportal/Control/ZoomSlider.js",
                "Geoportal/Util.js",
                "Geoportal/Control/ZoomBar.js",
                "Geoportal/Control/Copyright.js",
                "Geoportal/Control/GraphicScale.js",
                "Geoportal/Control/Projections.js",
                "Geoportal/Control/Floating.js",
                "Geoportal/Control/Form.js",
                "Geoportal/Control/MousePosition.js",
                "Geoportal/Control/Information.js",
                "Geoportal/Control/PageManager.js",
                "Geoportal/Control/CSW.js",
                "Geoportal/Control/LayerMetadata.js",
                "Geoportal/UI/Panel.js",
                "Geoportal/Control/Panel.js",
                "Geoportal/Control/PanelToggle.js",
                "Geoportal/Control/RemoveLayer.js",
                "Geoportal/Control/LayerOpacitySlider.js",
                "Geoportal/Control/LayerOpacity.js",
                "Geoportal/Control/ZoomToLayerMaxExtent.js",
                "Geoportal/Control/BasicLayerToolbar.js",
                // "Geoportal/Layer/WFS.js",//removed!
                "Geoportal/Format/WMC.js",
                "Geoportal/Format/WMC/v1_1_0_AutoConf.js",
                "Geoportal/GeoRMHandler.js",
                "Geoportal/Control/Logo.js",
                "Geoportal/Control/ToggleControl.js",
                "Geoportal/Control/ToolBox.js",
                "Geoportal/Control/NavToolbar.js",
                "Geoportal/Control/Loading.js",
                "Geoportal/Control/LayerAbstract.js",
                "Geoportal/Control/LayerLegend.js",
                "Geoportal/Control/LayerSwitcher.js",
                "Geoportal/Control/PrintMap.js",
                "Geoportal/Control/PrintMapDOM.js",
                "Geoportal/OLS/RequestHeader.js",
                "Geoportal/OLS/Request.js",
                "Geoportal/Layer/OpenLS/Core/LocationUtilityService.js",
                "Geoportal/Control/LocationUtilityService.js",
                "Geoportal/Control/AutoComplete.js",
                "Geoportal/Control/LocationUtilityService/GeoNames.js",
                "Geoportal/Control/LocationUtilityService/Geocode.js",
                "Geoportal/Control/LocationUtilityService/ReverseGeocode.js",
                "Geoportal/Control/SearchToolbar.js",
                "Geoportal/Control/TerritorySelector.js",
                "Geoportal/Popup.js",
                "Geoportal/UI/JQuery.js",
                "Geoportal/UI/JQuery/Panel.js",
                "Geoportal/Layer/Vector.js",
                "Geoportal/Control/Compass.js",
                "Geoportal/Tile.js",
                "Geoportal/Control/AddImageLayer.js",
                "Geoportal/Control/EditingToolbar.js",
                "Geoportal/Control/PermanentLogo.js",
                "Geoportal/Control/Measure.js",
                "Geoportal/Control/Measure/Azimuth.js",
                "Geoportal/Control/Measure/ElevationComponent.js",
                "Geoportal/Control/Measure/Elevation.js",
                "Geoportal/Control/Measure/ElevationPath.js", 
                "Geoportal/Control/Measure/ElevationRequest.js",
                "Geoportal/Control/MeasureToolbar.js",
                "Geoportal/Strategy.js",
                "Geoportal/Strategy/Tiled.js",
                "Geoportal/Popup/Anchored.js",
                "Geoportal/Handler.js",
                "Geoportal/Layer/Aggregate.js",
                "Geoportal/Handler/Path.js",
                "Geoportal/Handler/LengthRestrictedPath.js",
                "Geoportal/Format/Geoconcept.js",
                "Geoportal/Tile/Image.js",
                "Geoportal/Control/AddVectorLayer.js",
                "Geoportal/Control/EditFeature.js",
                "Geoportal/Layer/Vector/Tiled.js",
                "Geoportal/OLS/Building.js",
                "Geoportal/OLS/UOM/Distance/Altitude.js",
                "Geoportal/Format/XLS/v1_2.js",
                "Geoportal/Format/XLS/v1_2/LocationUtilityService.js",
                "Geoportal/Layer/GXT.js",
                "Geoportal/UI/JQuery/Button.js",
                "Geoportal/Layer/Grid.js",
                "Geoportal/Control/TermsOfService.js",
                "Geoportal/Layer/WMTS.js",
                "Geoportal/Control/DeleteFeature.js",
                "Geoportal/Control/LayerCatalog.js",
                "Geoportal/Control/DrawingToolbar.js",
                "Geoportal/Control/PanPanel.js",
                "Geoportal/Control/OverviewMap.js",
                "Geoportal/UI/JQuery/Mobile.js",
                "Geoportal/UI/Button.js",
                "Geoportal/Control/AddAttributeToLayer.js",
                "Geoportal/Control/SaveLayer.js",
                "Geoportal/Layer/WMS.js",
                "Geoportal/Control/Graticule.js",
                "Geoportal/Format/GPX/v1_0.js",
                "Geoportal/Layer/WMSC.js",
                "Geoportal/Control/LayerToolbar.js",
                "Geoportal/Control/LocationUtilityService/GeodeticFixedPoint.js",
                "Geoportal/Control/LocationUtilityService/CadastralParcel.js",
                "Geoportal/Control/LayerStyling.js",
                "Geoportal/Map.js",
                "Geoportal/Catalogue.js",
                "Geoportal/Catalogue/Config.js",
                "Geoportal/Viewer.js",
                "Geoportal/Viewer/Simple.js",
                "Geoportal/Viewer/Default.js",
                "Geoportal/Viewer/Standard.js",
                "Geoportal/Viewer/Mobile.js",
                "Geoportal/InterfaceViewer.js",
                "Geoportal/InterfaceViewer/JS.js",
                "Geoportal/InterfaceViewer/Flash.js",
                "Geoportal/InterfaceViewer/VG.js",
                "Geoportal/Loader.js",
                "Geoportal/Loader/JS.js",
                "Geoportal/Loader/Flash.js",
                "Geoportal/Loader/VG.js"
            ]; // etc.
        }

        // See http://trac.osgeo.org/openlayers/ticket/2933
        // use "parser-inserted scripts" for guaranteed execution order
        // http://hsivonen.iki.fi/script-execution/
        var allScriptTags= new Array(jsFiles.length);

        var host= Geoportal._getScriptLocation() + "lib/";
        for (var i= 0, len= jsFiles.length; i < len; i++) {
            allScriptTags[i]= "<script" +
                                " type='text/javascript'" +
                                " src='" + host + jsFiles[i] + "'" +
                                " charset='UTF-8'" +
                              "></script>";
        }
        document.write(allScriptTags.join(""));
    }
})();

/**
 * Constant: VERSION_NUMBER
 * {String} *"Geoportal 2.1.2 ; publicationDate=2015-04-02"*
 */
Geoportal.VERSION_NUMBER="Geoportal 2.1.2 ; publicationDate=2015-04-02";
